language: node_js
node_js:
- '0.11'
before_script:
- chmod +x deploy.sh
branches:
  only:
  - master
after_success: ./deploy.sh
env:
  global:
  - GH_REF: github.com/karthikb351/chennairains.git
notifications:
  slack:
    secure: prYpbsJvM1X4VVOaz0ygrRdFLqwPoTyLGgqNZThblvH6rMH5UvncVUR1loowCejNC913BwW6lZK3hyLuTtcWqW8l3oJx2UvcHiFR+1Q5ZLUrAd1Gn0+ZU8oOeMYCRAxpCjkRdo8BMwYtS66YQtSbsnhYm/CkUkmeUgUmpk3IcRhmhphDEW/QhIggzFQqr5pxiRRM4eSnwgHOERdDYZzxYKbzCXThWNg1Ny2umrYnXz2E6YIzYqUIZuUdFl4JsgaL8LaSibVEM/hGrVg2jwlT46jrIX+ACGiKnQ6xxuyLC+lRa6Td2KATE3bC05dkakY+Mzdbbf3Axs7hdzMR0UASfBZJymJFvr2402WUvO+HLLweEteMThUfnJ578o5NSv8MdQRnxwunsj10+lrlk0YyD/6DwlIvvykeHRY0wMMOh1GsbIixrUgSZWTGrT8sz+PTyhGKILRSYUoWa6c1pU0CKLWvNRxjU5mzz1NkB3mWyxBJG4iFbOoelsY9np0fBtpfqlyZfL2TvVXXEkHK2JChVq5tAohpcp+P64/6UA52IpjGxh/9EyWuNE7QkSZW7FMdUgzXppuLVc1igx48+rbnFZr1I6ksgD1h/SCNjGOsbfwfF3qjT37bC9LnON2UP1mArINyA29/5PG8aLx2KSxivKgbfMPxIxnW/jpqQBSMUnQ=
